name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      # - name: Build API Step 
      #   run: |
      #     cd api
      #     yarn install
      #     yarn build 

      - name: Build NextJS Step 
        run: |
          git fetch origin
          git checkout dist        
          git merge origin/master
          yarn install
          yarn build

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "[Build] Commit ${{ github.sha }}"
