name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      # - name: Build API Step 
      #   run: |
      #     cd api
      #     yarn install
      #     yarn build

      - name: Add .env file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./.env
          contents: |
            NODE_ENV=GITHUB
          write-mode: overwrite

      - name: Build NextJS Step 
        run: |
          mkdir out
          yarn install
          yarn build

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Move NextJS Build
        run: |
          mv package.json out
          mv .next out
          mv server out

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "[Build] Commit {sha}"
