name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      # - name: Build API Step 
      #   run: |
      #     cd api
      #     yarn install
      #     yarn build 

      - name: Build NextJS Step 
        run: |
          mkdir out
          yarn install
          yarn build
          mv package.json out
          mv .next out
          mv server out

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "[Build] Commit {sha}"