name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: |
          git checkout -b dist origin/dist
          git merge main
      - run: |
          yarn install --production --pure-lockfile
          node prepareCI
          yarn build
      - run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push