name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_GITHUB: true
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: node prepareCI
      - run: yarn build
      - run: git add -A
      - run: git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
      - uses: ad-m/github-push-action@master
        with:
          branch: dist
          force: true
