name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --production --pure-lockfile    

      - name: Build server and website
        run: |
          yarn build
          node prepareCI

      - run: |
        git add -A

      - name: Push from dev to prod branch.
        uses: Automattic/action-commit-to-branch@master
        with:
          dest_branch: 'dist'
          source_branch: 'main'
          commit_message: 'Automated build'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}