name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.16.0'
          cache: 'npm'

      - name: NextJS build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Update locales
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Update locales'

      - name: Prepare repository
        run: |
          git checkout -b dist
          git push --set-upstream origin dist
          git merge main

      - name: Install dependencies
        run: |
          npm install --omit=dev --force

      - name: Build server and website
        run: |
          npm run build

      - name: Prepare dist branch
        run: |
          rm .gitignore
          cp .gitignore_dist .gitignore

      - name: Push from main to dist branch.
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push
