name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: git checkout -b dist
      - run: git merge main
      - run: yarn install
      - run: node prepareCI
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy ${{ github.sha }}
          branch: dist